// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Year             int32              `json:"year"`
	Month            int32              `json:"month"`
	Body             string             `json:"body"`
	Status           string             `json:"status"`
	PublishChannel   pgtype.Text        `json:"publish_channel"`
	DiscordMessageID pgtype.Text        `json:"discord_message_id"`
	LastError        pgtype.Text        `json:"last_error"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	ActorType      string             `json:"actor_type"`
	ActorLabel     pgtype.Text        `json:"actor_label"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	BeforeState    []byte             `json:"before_state"`
	AfterState     []byte             `json:"after_state"`
	Result         string             `json:"result"`
	Ip             pgtype.Text        `json:"ip"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Meeting struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Year           int32              `json:"year"`
	Month          int32              `json:"month"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	MeetingUrl     pgtype.Text        `json:"meeting_url"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Year           int32              `json:"year"`
	Month          int32              `json:"month"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	DueDate        pgtype.Date        `json:"due_date"`
	ReferenceUrl   pgtype.Text        `json:"reference_url"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type TaskApproval struct {
	ID             pgtype.UUID        `json:"id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	ApproverUserID pgtype.UUID        `json:"approver_user_id"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	OidcSubject string             `json:"oidc_subject"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
