// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveTask = `-- name: ApproveTask :one
UPDATE task_approvals
SET approved_at = NOW()
WHERE task_id = $1
  AND approver_user_id = $2
  AND approved_at IS NULL
RETURNING id, task_id, approver_user_id, approved_at, created_at
`

type ApproveTaskParams struct {
	TaskID         pgtype.UUID `json:"task_id"`
	ApproverUserID pgtype.UUID `json:"approver_user_id"`
}

func (q *Queries) ApproveTask(ctx context.Context, arg ApproveTaskParams) (TaskApproval, error) {
	row := q.db.QueryRow(ctx, approveTask, arg.TaskID, arg.ApproverUserID)
	var i TaskApproval
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const completeAnnouncementPublish = `-- name: CompleteAnnouncementPublish :one
UPDATE announcements
SET status = 'published',
    discord_message_id = $2,
    last_error = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at
`

type CompleteAnnouncementPublishParams struct {
	ID               pgtype.UUID `json:"id"`
	DiscordMessageID pgtype.Text `json:"discord_message_id"`
}

func (q *Queries) CompleteAnnouncementPublish(ctx context.Context, arg CompleteAnnouncementPublishParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, completeAnnouncementPublish, arg.ID, arg.DiscordMessageID)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
  organization_id,
  actor_user_id,
  actor_type,
  actor_label,
  action,
  resource_type,
  resource_id,
  before_state,
  after_state,
  result,
  ip
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	ActorType      string      `json:"actor_type"`
	ActorLabel     pgtype.Text `json:"actor_label"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     pgtype.UUID `json:"resource_id"`
	BeforeState    []byte      `json:"before_state"`
	AfterState     []byte      `json:"after_state"`
	Result         string      `json:"result"`
	Ip             pgtype.Text `json:"ip"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.ActorType,
		arg.ActorLabel,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeState,
		arg.AfterState,
		arg.Result,
		arg.Ip,
	)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  organization_id,
  year,
  month,
  title,
  status,
  due_date,
  reference_url,
  assignee_id,
  created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, year, month, title, status, due_date, reference_url, assignee_id, created_by, version, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
	Month          int32       `json:"month"`
	Title          string      `json:"title"`
	Status         string      `json:"status"`
	DueDate        pgtype.Date `json:"due_date"`
	ReferenceUrl   pgtype.Text `json:"reference_url"`
	AssigneeID     pgtype.UUID `json:"assignee_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.OrganizationID,
		arg.Year,
		arg.Month,
		arg.Title,
		arg.Status,
		arg.DueDate,
		arg.ReferenceUrl,
		arg.AssigneeID,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.ReferenceUrl,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaskApproval = `-- name: CreateTaskApproval :exec
INSERT INTO task_approvals (task_id, approver_user_id)
VALUES ($1, $2)
`

type CreateTaskApprovalParams struct {
	TaskID         pgtype.UUID `json:"task_id"`
	ApproverUserID pgtype.UUID `json:"approver_user_id"`
}

func (q *Queries) CreateTaskApproval(ctx context.Context, arg CreateTaskApprovalParams) error {
	_, err := q.db.Exec(ctx, createTaskApproval, arg.TaskID, arg.ApproverUserID)
	return err
}

const createTaskApprovalWithState = `-- name: CreateTaskApprovalWithState :exec
INSERT INTO task_approvals (task_id, approver_user_id, approved_at)
VALUES ($1, $2, $3)
`

type CreateTaskApprovalWithStateParams struct {
	TaskID         pgtype.UUID        `json:"task_id"`
	ApproverUserID pgtype.UUID        `json:"approver_user_id"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) CreateTaskApprovalWithState(ctx context.Context, arg CreateTaskApprovalWithStateParams) error {
	_, err := q.db.Exec(ctx, createTaskApprovalWithState, arg.TaskID, arg.ApproverUserID, arg.ApprovedAt)
	return err
}

const deleteTask = `-- name: DeleteTask :one
UPDATE tasks
SET deleted_at = NOW(),
    version = version + 1,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NULL
RETURNING id, organization_id, year, month, title, status, due_date, reference_url, assignee_id, created_by, version, created_at, updated_at, deleted_at
`

type DeleteTaskParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
	Version        int32       `json:"version"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, deleteTask, arg.OrganizationID, arg.ID, arg.Version)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.ReferenceUrl,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTaskApprovalsByTaskID = `-- name: DeleteTaskApprovalsByTaskID :exec
DELETE FROM task_approvals
WHERE task_id = $1
`

func (q *Queries) DeleteTaskApprovalsByTaskID(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskApprovalsByTaskID, taskID)
	return err
}

const ensureOrganization = `-- name: EnsureOrganization :one
INSERT INTO organizations (slug, name)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, slug, name, created_at, updated_at
`

type EnsureOrganizationParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) EnsureOrganization(ctx context.Context, arg EnsureOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, ensureOrganization, arg.Slug, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureOrganizationMembership = `-- name: EnsureOrganizationMembership :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (organization_id, user_id) DO UPDATE
SET role = EXCLUDED.role
RETURNING id, organization_id, user_id, role, created_at
`

type EnsureOrganizationMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
}

func (q *Queries) EnsureOrganizationMembership(ctx context.Context, arg EnsureOrganizationMembershipParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, ensureOrganizationMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const failAnnouncementPublish = `-- name: FailAnnouncementPublish :one
UPDATE announcements
SET status = 'publish_failed',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at
`

type FailAnnouncementPublishParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailAnnouncementPublish(ctx context.Context, arg FailAnnouncementPublishParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, failAnnouncementPublish, arg.ID, arg.LastError)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at FROM announcements
WHERE id = $1
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnouncementByIDForOrg = `-- name: GetAnnouncementByIDForOrg :one
SELECT id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at FROM announcements
WHERE organization_id = $1
  AND id = $2
`

type GetAnnouncementByIDForOrgParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) GetAnnouncementByIDForOrg(ctx context.Context, arg GetAnnouncementByIDForOrgParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByIDForOrg, arg.OrganizationID, arg.ID)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnouncementByPeriod = `-- name: GetAnnouncementByPeriod :one
SELECT id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at FROM announcements
WHERE organization_id = $1
  AND year = $2
  AND month = $3
`

type GetAnnouncementByPeriodParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
	Month          int32       `json:"month"`
}

func (q *Queries) GetAnnouncementByPeriod(ctx context.Context, arg GetAnnouncementByPeriodParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByPeriod, arg.OrganizationID, arg.Year, arg.Month)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeetingByPeriod = `-- name: GetMeetingByPeriod :one
SELECT id, organization_id, year, month, scheduled_at, meeting_url, notes, status, updated_by, created_at, updated_at FROM meetings
WHERE organization_id = $1
  AND year = $2
  AND month = $3
`

type GetMeetingByPeriodParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
	Month          int32       `json:"month"`
}

func (q *Queries) GetMeetingByPeriod(ctx context.Context, arg GetMeetingByPeriodParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingByPeriod, arg.OrganizationID, arg.Year, arg.Month)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.ScheduledAt,
		&i.MeetingUrl,
		&i.Notes,
		&i.Status,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, created_at, updated_at FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at, u.oidc_subject, u.email, u.name
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1
  AND om.user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type GetOrganizationMemberRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	OidcSubject    string             `json:"oidc_subject"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (GetOrganizationMemberRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i GetOrganizationMemberRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, organization_id, year, month, title, status, due_date, reference_url, assignee_id, created_by, version, created_at, updated_at, deleted_at FROM tasks
WHERE organization_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.OrganizationID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.ReferenceUrl,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAnnouncementPeriods = `-- name: ListAnnouncementPeriods :many
SELECT year, month, status
FROM announcements
WHERE organization_id = $1
ORDER BY year DESC, month DESC
`

type ListAnnouncementPeriodsRow struct {
	Year   int32  `json:"year"`
	Month  int32  `json:"month"`
	Status string `json:"status"`
}

func (q *Queries) ListAnnouncementPeriods(ctx context.Context, organizationID pgtype.UUID) ([]ListAnnouncementPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementPeriods, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementPeriodsRow{}
	for rows.Next() {
		var i ListAnnouncementPeriodsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingPeriods = `-- name: ListMeetingPeriods :many
SELECT year, month, status
FROM meetings
WHERE organization_id = $1
ORDER BY year DESC, month DESC
`

type ListMeetingPeriodsRow struct {
	Year   int32  `json:"year"`
	Month  int32  `json:"month"`
	Status string `json:"status"`
}

func (q *Queries) ListMeetingPeriods(ctx context.Context, organizationID pgtype.UUID) ([]ListMeetingPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listMeetingPeriods, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingPeriodsRow{}
	for rows.Next() {
		var i ListMeetingPeriodsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT u.id, u.email, u.name, om.role
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1
ORDER BY u.name ASC
`

type ListOrganizationMembersRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
	Role  string      `json:"role"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID pgtype.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAnnouncementPublishRequests = `-- name: ListPendingAnnouncementPublishRequests :many
SELECT id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at
FROM announcements
WHERE status = 'publish_requested'
ORDER BY updated_at ASC
`

func (q *Queries) ListPendingAnnouncementPublishRequests(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listPendingAnnouncementPublishRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Year,
			&i.Month,
			&i.Body,
			&i.Status,
			&i.PublishChannel,
			&i.DiscordMessageID,
			&i.LastError,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskApprovalsByTaskID = `-- name: ListTaskApprovalsByTaskID :many
SELECT id, task_id, approver_user_id, approved_at, created_at FROM task_approvals
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTaskApprovalsByTaskID(ctx context.Context, taskID pgtype.UUID) ([]TaskApproval, error) {
	rows, err := q.db.Query(ctx, listTaskApprovalsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskApproval{}
	for rows.Next() {
		var i TaskApproval
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskApprovalsByTaskIDs = `-- name: ListTaskApprovalsByTaskIDs :many
SELECT id, task_id, approver_user_id, approved_at, created_at FROM task_approvals
WHERE task_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) ListTaskApprovalsByTaskIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]TaskApproval, error) {
	rows, err := q.db.Query(ctx, listTaskApprovalsByTaskIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskApproval{}
	for rows.Next() {
		var i TaskApproval
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskPeriodSummaries = `-- name: ListTaskPeriodSummaries :many
SELECT
  t.year,
  t.month,
  COUNT(*)::bigint AS task_count,
  COUNT(*) FILTER (WHERE t.status = 'done')::bigint AS done_task_count,
  COALESCE(SUM(approval_stats.required_count), 0)::bigint AS required_approvals,
  COALESCE(SUM(approval_stats.approved_count), 0)::bigint AS approved_approvals
FROM tasks t
LEFT JOIN LATERAL (
  SELECT
    COUNT(*)::bigint AS required_count,
    COUNT(*) FILTER (WHERE approved_at IS NOT NULL)::bigint AS approved_count
  FROM task_approvals ta
  WHERE ta.task_id = t.id
) approval_stats ON TRUE
WHERE t.organization_id = $1
  AND t.deleted_at IS NULL
GROUP BY t.year, t.month
ORDER BY t.year DESC, t.month DESC
`

type ListTaskPeriodSummariesRow struct {
	Year              int32 `json:"year"`
	Month             int32 `json:"month"`
	TaskCount         int64 `json:"task_count"`
	DoneTaskCount     int64 `json:"done_task_count"`
	RequiredApprovals int64 `json:"required_approvals"`
	ApprovedApprovals int64 `json:"approved_approvals"`
}

func (q *Queries) ListTaskPeriodSummaries(ctx context.Context, organizationID pgtype.UUID) ([]ListTaskPeriodSummariesRow, error) {
	rows, err := q.db.Query(ctx, listTaskPeriodSummaries, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskPeriodSummariesRow{}
	for rows.Next() {
		var i ListTaskPeriodSummariesRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.TaskCount,
			&i.DoneTaskCount,
			&i.RequiredApprovals,
			&i.ApprovedApprovals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPeriod = `-- name: ListTasksByPeriod :many
SELECT id, organization_id, year, month, title, status, due_date, reference_url, assignee_id, created_by, version, created_at, updated_at, deleted_at FROM tasks
WHERE organization_id = $1
  AND year = $2
  AND month = $3
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListTasksByPeriodParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
	Month          int32       `json:"month"`
}

func (q *Queries) ListTasksByPeriod(ctx context.Context, arg ListTasksByPeriodParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByPeriod, arg.OrganizationID, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Year,
			&i.Month,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.ReferenceUrl,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestAnnouncementPublish = `-- name: RequestAnnouncementPublish :one
UPDATE announcements
SET status = 'publish_requested',
    publish_channel = $3,
    last_error = NULL,
    updated_by = $4,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
RETURNING id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at
`

type RequestAnnouncementPublishParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
	PublishChannel pgtype.Text `json:"publish_channel"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
}

func (q *Queries) RequestAnnouncementPublish(ctx context.Context, arg RequestAnnouncementPublishParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, requestAnnouncementPublish,
		arg.OrganizationID,
		arg.ID,
		arg.PublishChannel,
		arg.UpdatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3,
    status = $4,
    due_date = $5,
    reference_url = $6,
    assignee_id = $7,
    version = version + 1,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND version = $8
  AND deleted_at IS NULL
RETURNING id, organization_id, year, month, title, status, due_date, reference_url, assignee_id, created_by, version, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ID             pgtype.UUID `json:"id"`
	Title          string      `json:"title"`
	Status         string      `json:"status"`
	DueDate        pgtype.Date `json:"due_date"`
	ReferenceUrl   pgtype.Text `json:"reference_url"`
	AssigneeID     pgtype.UUID `json:"assignee_id"`
	Version        int32       `json:"version"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.OrganizationID,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.DueDate,
		arg.ReferenceUrl,
		arg.AssigneeID,
		arg.Version,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.ReferenceUrl,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertAnnouncementDraft = `-- name: UpsertAnnouncementDraft :one
INSERT INTO announcements (
  organization_id,
  year,
  month,
  body,
  status,
  publish_channel,
  discord_message_id,
  last_error,
  updated_by
)
VALUES ($1, $2, $3, $4, 'draft', $5, NULL, NULL, $6)
ON CONFLICT (organization_id, year, month) DO UPDATE
SET body = EXCLUDED.body,
    publish_channel = COALESCE(EXCLUDED.publish_channel, announcements.publish_channel),
    status = 'draft',
    discord_message_id = NULL,
    last_error = NULL,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING id, organization_id, year, month, body, status, publish_channel, discord_message_id, last_error, updated_by, created_at, updated_at
`

type UpsertAnnouncementDraftParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
	Month          int32       `json:"month"`
	Body           string      `json:"body"`
	PublishChannel pgtype.Text `json:"publish_channel"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertAnnouncementDraft(ctx context.Context, arg UpsertAnnouncementDraftParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, upsertAnnouncementDraft,
		arg.OrganizationID,
		arg.Year,
		arg.Month,
		arg.Body,
		arg.PublishChannel,
		arg.UpdatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.Body,
		&i.Status,
		&i.PublishChannel,
		&i.DiscordMessageID,
		&i.LastError,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMeeting = `-- name: UpsertMeeting :one
INSERT INTO meetings (
  organization_id,
  year,
  month,
  scheduled_at,
  meeting_url,
  notes,
  status,
  updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (organization_id, year, month) DO UPDATE
SET scheduled_at = EXCLUDED.scheduled_at,
    meeting_url = EXCLUDED.meeting_url,
    notes = EXCLUDED.notes,
    status = EXCLUDED.status,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING id, organization_id, year, month, scheduled_at, meeting_url, notes, status, updated_by, created_at, updated_at
`

type UpsertMeetingParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Year           int32              `json:"year"`
	Month          int32              `json:"month"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	MeetingUrl     pgtype.Text        `json:"meeting_url"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpsertMeeting(ctx context.Context, arg UpsertMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, upsertMeeting,
		arg.OrganizationID,
		arg.Year,
		arg.Month,
		arg.ScheduledAt,
		arg.MeetingUrl,
		arg.Notes,
		arg.Status,
		arg.UpdatedBy,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Year,
		&i.Month,
		&i.ScheduledAt,
		&i.MeetingUrl,
		&i.Notes,
		&i.Status,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_subject, email, name)
VALUES ($1, $2, $3)
ON CONFLICT (oidc_subject) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, oidc_subject, email, name, created_at, updated_at
`

type UpsertUserParams struct {
	OidcSubject string `json:"oidc_subject"`
	Email       string `json:"email"`
	Name        string `json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.OidcSubject, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
