// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	BotTokenScopes   = "BotToken.Scopes"
)

// Defines values for AnnouncementStatus.
const (
	Draft            AnnouncementStatus = "draft"
	PublishFailed    AnnouncementStatus = "publish_failed"
	PublishRequested AnnouncementStatus = "publish_requested"
	Published        AnnouncementStatus = "published"
)

// Defines values for ApprovalState.
const (
	Approved          ApprovalState = "approved"
	NotRequired       ApprovalState = "not_required"
	PartiallyApproved ApprovalState = "partially_approved"
	Pending           ApprovalState = "pending"
)

// Defines values for MeetingStatus.
const (
	Cancelled MeetingStatus = "cancelled"
	Completed MeetingStatus = "completed"
	Planned   MeetingStatus = "planned"
)

// Defines values for OrganizationRole.
const (
	EDITOR OrganizationRole = "EDITOR"
	OWNER  OrganizationRole = "OWNER"
	VIEWER OrganizationRole = "VIEWER"
)

// Defines values for TaskStatus.
const (
	Done       TaskStatus = "done"
	InProgress TaskStatus = "in_progress"
	Todo       TaskStatus = "todo"
)

// ActorUser defines model for ActorUser.
type ActorUser struct {
	Email   openapi_types.Email `json:"email"`
	Id      openapi_types.UUID  `json:"id"`
	Name    string              `json:"name"`
	Role    OrganizationRole    `json:"role"`
	Subject string              `json:"subject"`
}

// Announcement defines model for Announcement.
type Announcement struct {
	Body             string             `json:"body"`
	DiscordMessageId *string            `json:"discord_message_id"`
	Id               openapi_types.UUID `json:"id"`
	LastError        *string            `json:"last_error"`
	Month            int                `json:"month"`
	PublishChannel   *string            `json:"publish_channel"`
	Status           AnnouncementStatus `json:"status"`
	Year             int                `json:"year"`
}

// AnnouncementStatus defines model for AnnouncementStatus.
type AnnouncementStatus string

// ApprovalState defines model for ApprovalState.
type ApprovalState string

// CompletePublishRequest defines model for CompletePublishRequest.
type CompletePublishRequest struct {
	DiscordMessageId string `json:"discord_message_id"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	ApproverIds  []openapi_types.UUID `json:"approver_ids"`
	AssigneeId   *openapi_types.UUID  `json:"assignee_id"`
	DueDate      *openapi_types.Date  `json:"due_date"`
	Month        int                  `json:"month"`
	ReferenceUrl *string              `json:"reference_url"`
	Status       TaskStatus           `json:"status"`
	Title        string               `json:"title"`
	Year         int                  `json:"year"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FailPublishRequest defines model for FailPublishRequest.
type FailPublishRequest struct {
	Error string `json:"error"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Organization Organization `json:"organization"`
	User         ActorUser    `json:"user"`
}

// Meeting defines model for Meeting.
type Meeting struct {
	Id          openapi_types.UUID `json:"id"`
	MeetingUrl  *string            `json:"meeting_url"`
	Month       int                `json:"month"`
	Notes       *string            `json:"notes"`
	ScheduledAt *time.Time         `json:"scheduled_at"`
	Status      MeetingStatus      `json:"status"`
	Year        int                `json:"year"`
}

// MeetingStatus defines model for MeetingStatus.
type MeetingStatus string

// Member defines model for Member.
type Member struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`
	Role  OrganizationRole    `json:"role"`
}

// MembersResponse defines model for MembersResponse.
type MembersResponse struct {
	Members []Member `json:"members"`
}

// Organization defines model for Organization.
type Organization struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// OrganizationRole defines model for OrganizationRole.
type OrganizationRole string

// PublishAnnouncementRequest defines model for PublishAnnouncementRequest.
type PublishAnnouncementRequest struct {
	PublishChannel string `json:"publish_channel"`
}

// PublishRequest defines model for PublishRequest.
type PublishRequest struct {
	AnnouncementId openapi_types.UUID `json:"announcement_id"`
	Body           string             `json:"body"`
	Month          int                `json:"month"`
	PublishChannel string             `json:"publish_channel"`
	Year           int                `json:"year"`
}

// PublishRequestsResponse defines model for PublishRequestsResponse.
type PublishRequestsResponse struct {
	Requests []PublishRequest `json:"requests"`
}

// PutAnnouncementRequest defines model for PutAnnouncementRequest.
type PutAnnouncementRequest struct {
	Body           string  `json:"body"`
	PublishChannel *string `json:"publish_channel"`
}

// PutMeetingRequest defines model for PutMeetingRequest.
type PutMeetingRequest struct {
	MeetingUrl  *string       `json:"meeting_url"`
	Notes       *string       `json:"notes"`
	ScheduledAt *time.Time    `json:"scheduled_at"`
	Status      MeetingStatus `json:"status"`
}

// Task defines model for Task.
type Task struct {
	ApprovalState       ApprovalState        `json:"approval_state"`
	ApprovedApproverIds []openapi_types.UUID `json:"approved_approver_ids"`
	ApproverIds         []openapi_types.UUID `json:"approver_ids"`
	AssigneeId          *openapi_types.UUID  `json:"assignee_id"`
	CreatedBy           *openapi_types.UUID  `json:"created_by,omitempty"`
	DueDate             *openapi_types.Date  `json:"due_date"`
	Id                  openapi_types.UUID   `json:"id"`
	Month               int                  `json:"month"`
	ReferenceUrl        *string              `json:"reference_url"`
	Status              TaskStatus           `json:"status"`
	Title               string               `json:"title"`
	Version             int                  `json:"version"`
	Year                int                  `json:"year"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	Tasks []Task `json:"tasks"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	ApproverIds  []openapi_types.UUID `json:"approver_ids"`
	AssigneeId   *openapi_types.UUID  `json:"assignee_id"`
	DueDate      *openapi_types.Date  `json:"due_date"`
	ReferenceUrl *string              `json:"reference_url"`
	Status       TaskStatus           `json:"status"`
	Title        string               `json:"title"`
	Version      int                  `json:"version"`
}

// WorkflowPeriod defines model for WorkflowPeriod.
type WorkflowPeriod struct {
	AnnouncementStatus   string `json:"announcement_status"`
	MeetingStatus        string `json:"meeting_status"`
	Month                int    `json:"month"`
	NextStageReady       bool   `json:"next_stage_ready"`
	TaskCompletionStatus string `json:"task_completion_status"`
	Year                 int    `json:"year"`
}

// WorkflowPeriodsResponse defines model for WorkflowPeriodsResponse.
type WorkflowPeriodsResponse struct {
	Periods []WorkflowPeriod `json:"periods"`
}

// IdParam defines model for IdParam.
type IdParam = openapi_types.UUID

// MonthParam defines model for MonthParam.
type MonthParam = int

// MonthQuery defines model for MonthQuery.
type MonthQuery = int

// YearParam defines model for YearParam.
type YearParam = int

// YearQuery defines model for YearQuery.
type YearQuery = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	Year  YearQuery  `form:"year" json:"year"`
	Month MonthQuery `form:"month" json:"month"`
}

// DeleteTaskParams defines parameters for DeleteTask.
type DeleteTaskParams struct {
	Version int `form:"version" json:"version"`
}

// PublishAnnouncementJSONRequestBody defines body for PublishAnnouncement for application/json ContentType.
type PublishAnnouncementJSONRequestBody = PublishAnnouncementRequest

// PutAnnouncementJSONRequestBody defines body for PutAnnouncement for application/json ContentType.
type PutAnnouncementJSONRequestBody = PutAnnouncementRequest

// PutMeetingJSONRequestBody defines body for PutMeeting for application/json ContentType.
type PutMeetingJSONRequestBody = PutMeetingRequest

// PostTaskJSONRequestBody defines body for PostTask for application/json ContentType.
type PostTaskJSONRequestBody = CreateTaskRequest

// PatchTaskJSONRequestBody defines body for PatchTask for application/json ContentType.
type PatchTaskJSONRequestBody = UpdateTaskRequest

// CompleteAnnouncementPublishRequestJSONRequestBody defines body for CompleteAnnouncementPublishRequest for application/json ContentType.
type CompleteAnnouncementPublishRequestJSONRequestBody = CompletePublishRequest

// FailAnnouncementPublishRequestJSONRequestBody defines body for FailAnnouncementPublishRequest for application/json ContentType.
type FailAnnouncementPublishRequestJSONRequestBody = FailPublishRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/announcements/{id}/publish)
	PublishAnnouncement(ctx echo.Context, id IdParam) error

	// (GET /api/v1/announcements/{year}/{month})
	GetAnnouncement(ctx echo.Context, year YearParam, month MonthParam) error

	// (PUT /api/v1/announcements/{year}/{month})
	PutAnnouncement(ctx echo.Context, year YearParam, month MonthParam) error

	// (GET /api/v1/me)
	GetMe(ctx echo.Context) error

	// (GET /api/v1/meetings/{year}/{month})
	GetMeeting(ctx echo.Context, year YearParam, month MonthParam) error

	// (PUT /api/v1/meetings/{year}/{month})
	PutMeeting(ctx echo.Context, year YearParam, month MonthParam) error

	// (GET /api/v1/members)
	GetMembers(ctx echo.Context) error

	// (GET /api/v1/tasks)
	GetTasks(ctx echo.Context, params GetTasksParams) error

	// (POST /api/v1/tasks)
	PostTask(ctx echo.Context) error

	// (DELETE /api/v1/tasks/{id})
	DeleteTask(ctx echo.Context, id IdParam, params DeleteTaskParams) error

	// (PATCH /api/v1/tasks/{id})
	PatchTask(ctx echo.Context, id IdParam) error

	// (POST /api/v1/tasks/{id}/approve)
	ApproveTask(ctx echo.Context, id IdParam) error

	// (GET /api/v1/workflow-periods)
	GetWorkflowPeriods(ctx echo.Context) error

	// (GET /internal/v1/announcement-publish-requests)
	GetAnnouncementPublishRequests(ctx echo.Context) error

	// (POST /internal/v1/announcement-publish-requests/{id}/complete)
	CompleteAnnouncementPublishRequest(ctx echo.Context, id IdParam) error

	// (POST /internal/v1/announcement-publish-requests/{id}/fail)
	FailAnnouncementPublishRequest(ctx echo.Context, id IdParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PublishAnnouncement converts echo context to params.
func (w *ServerInterfaceWrapper) PublishAnnouncement(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PublishAnnouncement(ctx, id)
	return err
}

// GetAnnouncement converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnnouncement(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "year" -------------
	var year YearParam

	err = runtime.BindStyledParameterWithOptions("simple", "year", ctx.Param("year"), &year, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// ------------- Path parameter "month" -------------
	var month MonthParam

	err = runtime.BindStyledParameterWithOptions("simple", "month", ctx.Param("month"), &month, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnnouncement(ctx, year, month)
	return err
}

// PutAnnouncement converts echo context to params.
func (w *ServerInterfaceWrapper) PutAnnouncement(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "year" -------------
	var year YearParam

	err = runtime.BindStyledParameterWithOptions("simple", "year", ctx.Param("year"), &year, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// ------------- Path parameter "month" -------------
	var month MonthParam

	err = runtime.BindStyledParameterWithOptions("simple", "month", ctx.Param("month"), &month, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutAnnouncement(ctx, year, month)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// GetMeeting converts echo context to params.
func (w *ServerInterfaceWrapper) GetMeeting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "year" -------------
	var year YearParam

	err = runtime.BindStyledParameterWithOptions("simple", "year", ctx.Param("year"), &year, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// ------------- Path parameter "month" -------------
	var month MonthParam

	err = runtime.BindStyledParameterWithOptions("simple", "month", ctx.Param("month"), &month, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMeeting(ctx, year, month)
	return err
}

// PutMeeting converts echo context to params.
func (w *ServerInterfaceWrapper) PutMeeting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "year" -------------
	var year YearParam

	err = runtime.BindStyledParameterWithOptions("simple", "year", ctx.Param("year"), &year, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// ------------- Path parameter "month" -------------
	var month MonthParam

	err = runtime.BindStyledParameterWithOptions("simple", "month", ctx.Param("month"), &month, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutMeeting(ctx, year, month)
	return err
}

// GetMembers converts echo context to params.
func (w *ServerInterfaceWrapper) GetMembers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMembers(ctx)
	return err
}

// GetTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetTasks(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams
	// ------------- Required query parameter "year" -------------

	err = runtime.BindQueryParameter("form", true, true, "year", ctx.QueryParams(), &params.Year)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// ------------- Required query parameter "month" -------------

	err = runtime.BindQueryParameter("form", true, true, "month", ctx.QueryParams(), &params.Month)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTasks(ctx, params)
	return err
}

// PostTask converts echo context to params.
func (w *ServerInterfaceWrapper) PostTask(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTask(ctx)
	return err
}

// DeleteTask converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTaskParams
	// ------------- Required query parameter "version" -------------

	err = runtime.BindQueryParameter("form", true, true, "version", ctx.QueryParams(), &params.Version)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTask(ctx, id, params)
	return err
}

// PatchTask converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTask(ctx, id)
	return err
}

// ApproveTask converts echo context to params.
func (w *ServerInterfaceWrapper) ApproveTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApproveTask(ctx, id)
	return err
}

// GetWorkflowPeriods converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkflowPeriods(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkflowPeriods(ctx)
	return err
}

// GetAnnouncementPublishRequests converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnnouncementPublishRequests(ctx echo.Context) error {
	var err error

	ctx.Set(BotTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnnouncementPublishRequests(ctx)
	return err
}

// CompleteAnnouncementPublishRequest converts echo context to params.
func (w *ServerInterfaceWrapper) CompleteAnnouncementPublishRequest(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BotTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CompleteAnnouncementPublishRequest(ctx, id)
	return err
}

// FailAnnouncementPublishRequest converts echo context to params.
func (w *ServerInterfaceWrapper) FailAnnouncementPublishRequest(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BotTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FailAnnouncementPublishRequest(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/announcements/:id/publish", wrapper.PublishAnnouncement)
	router.GET(baseURL+"/api/v1/announcements/:year/:month", wrapper.GetAnnouncement)
	router.PUT(baseURL+"/api/v1/announcements/:year/:month", wrapper.PutAnnouncement)
	router.GET(baseURL+"/api/v1/me", wrapper.GetMe)
	router.GET(baseURL+"/api/v1/meetings/:year/:month", wrapper.GetMeeting)
	router.PUT(baseURL+"/api/v1/meetings/:year/:month", wrapper.PutMeeting)
	router.GET(baseURL+"/api/v1/members", wrapper.GetMembers)
	router.GET(baseURL+"/api/v1/tasks", wrapper.GetTasks)
	router.POST(baseURL+"/api/v1/tasks", wrapper.PostTask)
	router.DELETE(baseURL+"/api/v1/tasks/:id", wrapper.DeleteTask)
	router.PATCH(baseURL+"/api/v1/tasks/:id", wrapper.PatchTask)
	router.POST(baseURL+"/api/v1/tasks/:id/approve", wrapper.ApproveTask)
	router.GET(baseURL+"/api/v1/workflow-periods", wrapper.GetWorkflowPeriods)
	router.GET(baseURL+"/internal/v1/announcement-publish-requests", wrapper.GetAnnouncementPublishRequests)
	router.POST(baseURL+"/internal/v1/announcement-publish-requests/:id/complete", wrapper.CompleteAnnouncementPublishRequest)
	router.POST(baseURL+"/internal/v1/announcement-publish-requests/:id/fail", wrapper.FailAnnouncementPublishRequest)

}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type PublishAnnouncementRequestObject struct {
	Id   IdParam `json:"id"`
	Body *PublishAnnouncementJSONRequestBody
}

type PublishAnnouncementResponseObject interface {
	VisitPublishAnnouncementResponse(w http.ResponseWriter) error
}

type PublishAnnouncement200JSONResponse Announcement

func (response PublishAnnouncement200JSONResponse) VisitPublishAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PublishAnnouncement400JSONResponse struct{ BadRequestJSONResponse }

func (response PublishAnnouncement400JSONResponse) VisitPublishAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PublishAnnouncement403JSONResponse struct{ ForbiddenJSONResponse }

func (response PublishAnnouncement403JSONResponse) VisitPublishAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PublishAnnouncement404JSONResponse struct{ NotFoundJSONResponse }

func (response PublishAnnouncement404JSONResponse) VisitPublishAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAnnouncementRequestObject struct {
	Year  YearParam  `json:"year"`
	Month MonthParam `json:"month"`
}

type GetAnnouncementResponseObject interface {
	VisitGetAnnouncementResponse(w http.ResponseWriter) error
}

type GetAnnouncement200JSONResponse Announcement

func (response GetAnnouncement200JSONResponse) VisitGetAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnnouncement404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAnnouncement404JSONResponse) VisitGetAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutAnnouncementRequestObject struct {
	Year  YearParam  `json:"year"`
	Month MonthParam `json:"month"`
	Body  *PutAnnouncementJSONRequestBody
}

type PutAnnouncementResponseObject interface {
	VisitPutAnnouncementResponse(w http.ResponseWriter) error
}

type PutAnnouncement200JSONResponse Announcement

func (response PutAnnouncement200JSONResponse) VisitPutAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutAnnouncement400JSONResponse struct{ BadRequestJSONResponse }

func (response PutAnnouncement400JSONResponse) VisitPutAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutAnnouncement403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutAnnouncement403JSONResponse) VisitPutAnnouncementResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMeetingRequestObject struct {
	Year  YearParam  `json:"year"`
	Month MonthParam `json:"month"`
}

type GetMeetingResponseObject interface {
	VisitGetMeetingResponse(w http.ResponseWriter) error
}

type GetMeeting200JSONResponse Meeting

func (response GetMeeting200JSONResponse) VisitGetMeetingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMeeting404JSONResponse struct{ NotFoundJSONResponse }

func (response GetMeeting404JSONResponse) VisitGetMeetingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutMeetingRequestObject struct {
	Year  YearParam  `json:"year"`
	Month MonthParam `json:"month"`
	Body  *PutMeetingJSONRequestBody
}

type PutMeetingResponseObject interface {
	VisitPutMeetingResponse(w http.ResponseWriter) error
}

type PutMeeting200JSONResponse Meeting

func (response PutMeeting200JSONResponse) VisitPutMeetingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutMeeting400JSONResponse struct{ BadRequestJSONResponse }

func (response PutMeeting400JSONResponse) VisitPutMeetingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutMeeting403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutMeeting403JSONResponse) VisitPutMeetingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetMembersRequestObject struct {
}

type GetMembersResponseObject interface {
	VisitGetMembersResponse(w http.ResponseWriter) error
}

type GetMembers200JSONResponse MembersResponse

func (response GetMembers200JSONResponse) VisitGetMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTasksRequestObject struct {
	Params GetTasksParams
}

type GetTasksResponseObject interface {
	VisitGetTasksResponse(w http.ResponseWriter) error
}

type GetTasks200JSONResponse TasksResponse

func (response GetTasks200JSONResponse) VisitGetTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTasks400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTasks400JSONResponse) VisitGetTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostTaskRequestObject struct {
	Body *PostTaskJSONRequestBody
}

type PostTaskResponseObject interface {
	VisitPostTaskResponse(w http.ResponseWriter) error
}

type PostTask201JSONResponse Task

func (response PostTask201JSONResponse) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostTask400JSONResponse struct{ BadRequestJSONResponse }

func (response PostTask400JSONResponse) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostTask403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostTask403JSONResponse) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTaskRequestObject struct {
	Id     IdParam `json:"id"`
	Params DeleteTaskParams
}

type DeleteTaskResponseObject interface {
	VisitDeleteTaskResponse(w http.ResponseWriter) error
}

type DeleteTask204Response struct {
}

func (response DeleteTask204Response) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTask400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteTask400JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteTask403JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteTask404JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTask409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteTask409JSONResponse) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PatchTaskRequestObject struct {
	Id   IdParam `json:"id"`
	Body *PatchTaskJSONRequestBody
}

type PatchTaskResponseObject interface {
	VisitPatchTaskResponse(w http.ResponseWriter) error
}

type PatchTask200JSONResponse Task

func (response PatchTask200JSONResponse) VisitPatchTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchTask400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchTask400JSONResponse) VisitPatchTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchTask403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchTask403JSONResponse) VisitPatchTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchTask404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchTask404JSONResponse) VisitPatchTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchTask409JSONResponse struct{ ConflictJSONResponse }

func (response PatchTask409JSONResponse) VisitPatchTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ApproveTaskRequestObject struct {
	Id IdParam `json:"id"`
}

type ApproveTaskResponseObject interface {
	VisitApproveTaskResponse(w http.ResponseWriter) error
}

type ApproveTask200JSONResponse Task

func (response ApproveTask200JSONResponse) VisitApproveTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApproveTask403JSONResponse struct{ ForbiddenJSONResponse }

func (response ApproveTask403JSONResponse) VisitApproveTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ApproveTask404JSONResponse struct{ NotFoundJSONResponse }

func (response ApproveTask404JSONResponse) VisitApproveTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApproveTask409JSONResponse struct{ ConflictJSONResponse }

func (response ApproveTask409JSONResponse) VisitApproveTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkflowPeriodsRequestObject struct {
}

type GetWorkflowPeriodsResponseObject interface {
	VisitGetWorkflowPeriodsResponse(w http.ResponseWriter) error
}

type GetWorkflowPeriods200JSONResponse WorkflowPeriodsResponse

func (response GetWorkflowPeriods200JSONResponse) VisitGetWorkflowPeriodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnnouncementPublishRequestsRequestObject struct {
}

type GetAnnouncementPublishRequestsResponseObject interface {
	VisitGetAnnouncementPublishRequestsResponse(w http.ResponseWriter) error
}

type GetAnnouncementPublishRequests200JSONResponse PublishRequestsResponse

func (response GetAnnouncementPublishRequests200JSONResponse) VisitGetAnnouncementPublishRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteAnnouncementPublishRequestRequestObject struct {
	Id   IdParam `json:"id"`
	Body *CompleteAnnouncementPublishRequestJSONRequestBody
}

type CompleteAnnouncementPublishRequestResponseObject interface {
	VisitCompleteAnnouncementPublishRequestResponse(w http.ResponseWriter) error
}

type CompleteAnnouncementPublishRequest200JSONResponse Announcement

func (response CompleteAnnouncementPublishRequest200JSONResponse) VisitCompleteAnnouncementPublishRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteAnnouncementPublishRequest404JSONResponse struct{ NotFoundJSONResponse }

func (response CompleteAnnouncementPublishRequest404JSONResponse) VisitCompleteAnnouncementPublishRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FailAnnouncementPublishRequestRequestObject struct {
	Id   IdParam `json:"id"`
	Body *FailAnnouncementPublishRequestJSONRequestBody
}

type FailAnnouncementPublishRequestResponseObject interface {
	VisitFailAnnouncementPublishRequestResponse(w http.ResponseWriter) error
}

type FailAnnouncementPublishRequest200JSONResponse Announcement

func (response FailAnnouncementPublishRequest200JSONResponse) VisitFailAnnouncementPublishRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FailAnnouncementPublishRequest404JSONResponse struct{ NotFoundJSONResponse }

func (response FailAnnouncementPublishRequest404JSONResponse) VisitFailAnnouncementPublishRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/announcements/{id}/publish)
	PublishAnnouncement(ctx context.Context, request PublishAnnouncementRequestObject) (PublishAnnouncementResponseObject, error)

	// (GET /api/v1/announcements/{year}/{month})
	GetAnnouncement(ctx context.Context, request GetAnnouncementRequestObject) (GetAnnouncementResponseObject, error)

	// (PUT /api/v1/announcements/{year}/{month})
	PutAnnouncement(ctx context.Context, request PutAnnouncementRequestObject) (PutAnnouncementResponseObject, error)

	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)

	// (GET /api/v1/meetings/{year}/{month})
	GetMeeting(ctx context.Context, request GetMeetingRequestObject) (GetMeetingResponseObject, error)

	// (PUT /api/v1/meetings/{year}/{month})
	PutMeeting(ctx context.Context, request PutMeetingRequestObject) (PutMeetingResponseObject, error)

	// (GET /api/v1/members)
	GetMembers(ctx context.Context, request GetMembersRequestObject) (GetMembersResponseObject, error)

	// (GET /api/v1/tasks)
	GetTasks(ctx context.Context, request GetTasksRequestObject) (GetTasksResponseObject, error)

	// (POST /api/v1/tasks)
	PostTask(ctx context.Context, request PostTaskRequestObject) (PostTaskResponseObject, error)

	// (DELETE /api/v1/tasks/{id})
	DeleteTask(ctx context.Context, request DeleteTaskRequestObject) (DeleteTaskResponseObject, error)

	// (PATCH /api/v1/tasks/{id})
	PatchTask(ctx context.Context, request PatchTaskRequestObject) (PatchTaskResponseObject, error)

	// (POST /api/v1/tasks/{id}/approve)
	ApproveTask(ctx context.Context, request ApproveTaskRequestObject) (ApproveTaskResponseObject, error)

	// (GET /api/v1/workflow-periods)
	GetWorkflowPeriods(ctx context.Context, request GetWorkflowPeriodsRequestObject) (GetWorkflowPeriodsResponseObject, error)

	// (GET /internal/v1/announcement-publish-requests)
	GetAnnouncementPublishRequests(ctx context.Context, request GetAnnouncementPublishRequestsRequestObject) (GetAnnouncementPublishRequestsResponseObject, error)

	// (POST /internal/v1/announcement-publish-requests/{id}/complete)
	CompleteAnnouncementPublishRequest(ctx context.Context, request CompleteAnnouncementPublishRequestRequestObject) (CompleteAnnouncementPublishRequestResponseObject, error)

	// (POST /internal/v1/announcement-publish-requests/{id}/fail)
	FailAnnouncementPublishRequest(ctx context.Context, request FailAnnouncementPublishRequestRequestObject) (FailAnnouncementPublishRequestResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PublishAnnouncement operation middleware
func (sh *strictHandler) PublishAnnouncement(ctx echo.Context, id IdParam) error {
	var request PublishAnnouncementRequestObject

	request.Id = id

	var body PublishAnnouncementJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PublishAnnouncement(ctx.Request().Context(), request.(PublishAnnouncementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishAnnouncement")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PublishAnnouncementResponseObject); ok {
		return validResponse.VisitPublishAnnouncementResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAnnouncement operation middleware
func (sh *strictHandler) GetAnnouncement(ctx echo.Context, year YearParam, month MonthParam) error {
	var request GetAnnouncementRequestObject

	request.Year = year
	request.Month = month

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnnouncement(ctx.Request().Context(), request.(GetAnnouncementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnnouncement")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAnnouncementResponseObject); ok {
		return validResponse.VisitGetAnnouncementResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutAnnouncement operation middleware
func (sh *strictHandler) PutAnnouncement(ctx echo.Context, year YearParam, month MonthParam) error {
	var request PutAnnouncementRequestObject

	request.Year = year
	request.Month = month

	var body PutAnnouncementJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutAnnouncement(ctx.Request().Context(), request.(PutAnnouncementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutAnnouncement")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutAnnouncementResponseObject); ok {
		return validResponse.VisitPutAnnouncementResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMeeting operation middleware
func (sh *strictHandler) GetMeeting(ctx echo.Context, year YearParam, month MonthParam) error {
	var request GetMeetingRequestObject

	request.Year = year
	request.Month = month

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMeeting(ctx.Request().Context(), request.(GetMeetingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMeeting")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeetingResponseObject); ok {
		return validResponse.VisitGetMeetingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutMeeting operation middleware
func (sh *strictHandler) PutMeeting(ctx echo.Context, year YearParam, month MonthParam) error {
	var request PutMeetingRequestObject

	request.Year = year
	request.Month = month

	var body PutMeetingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutMeeting(ctx.Request().Context(), request.(PutMeetingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutMeeting")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutMeetingResponseObject); ok {
		return validResponse.VisitPutMeetingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMembers operation middleware
func (sh *strictHandler) GetMembers(ctx echo.Context) error {
	var request GetMembersRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMembers(ctx.Request().Context(), request.(GetMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMembers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMembersResponseObject); ok {
		return validResponse.VisitGetMembersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTasks operation middleware
func (sh *strictHandler) GetTasks(ctx echo.Context, params GetTasksParams) error {
	var request GetTasksRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTasks(ctx.Request().Context(), request.(GetTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTasksResponseObject); ok {
		return validResponse.VisitGetTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostTask operation middleware
func (sh *strictHandler) PostTask(ctx echo.Context) error {
	var request PostTaskRequestObject

	var body PostTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostTask(ctx.Request().Context(), request.(PostTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostTaskResponseObject); ok {
		return validResponse.VisitPostTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTask operation middleware
func (sh *strictHandler) DeleteTask(ctx echo.Context, id IdParam, params DeleteTaskParams) error {
	var request DeleteTaskRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTask(ctx.Request().Context(), request.(DeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTaskResponseObject); ok {
		return validResponse.VisitDeleteTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchTask operation middleware
func (sh *strictHandler) PatchTask(ctx echo.Context, id IdParam) error {
	var request PatchTaskRequestObject

	request.Id = id

	var body PatchTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchTask(ctx.Request().Context(), request.(PatchTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchTaskResponseObject); ok {
		return validResponse.VisitPatchTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ApproveTask operation middleware
func (sh *strictHandler) ApproveTask(ctx echo.Context, id IdParam) error {
	var request ApproveTaskRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveTask(ctx.Request().Context(), request.(ApproveTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ApproveTaskResponseObject); ok {
		return validResponse.VisitApproveTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetWorkflowPeriods operation middleware
func (sh *strictHandler) GetWorkflowPeriods(ctx echo.Context) error {
	var request GetWorkflowPeriodsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkflowPeriods(ctx.Request().Context(), request.(GetWorkflowPeriodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkflowPeriods")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWorkflowPeriodsResponseObject); ok {
		return validResponse.VisitGetWorkflowPeriodsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAnnouncementPublishRequests operation middleware
func (sh *strictHandler) GetAnnouncementPublishRequests(ctx echo.Context) error {
	var request GetAnnouncementPublishRequestsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnnouncementPublishRequests(ctx.Request().Context(), request.(GetAnnouncementPublishRequestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnnouncementPublishRequests")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAnnouncementPublishRequestsResponseObject); ok {
		return validResponse.VisitGetAnnouncementPublishRequestsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CompleteAnnouncementPublishRequest operation middleware
func (sh *strictHandler) CompleteAnnouncementPublishRequest(ctx echo.Context, id IdParam) error {
	var request CompleteAnnouncementPublishRequestRequestObject

	request.Id = id

	var body CompleteAnnouncementPublishRequestJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteAnnouncementPublishRequest(ctx.Request().Context(), request.(CompleteAnnouncementPublishRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteAnnouncementPublishRequest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CompleteAnnouncementPublishRequestResponseObject); ok {
		return validResponse.VisitCompleteAnnouncementPublishRequestResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// FailAnnouncementPublishRequest operation middleware
func (sh *strictHandler) FailAnnouncementPublishRequest(ctx echo.Context, id IdParam) error {
	var request FailAnnouncementPublishRequestRequestObject

	request.Id = id

	var body FailAnnouncementPublishRequestJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FailAnnouncementPublishRequest(ctx.Request().Context(), request.(FailAnnouncementPublishRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FailAnnouncementPublishRequest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(FailAnnouncementPublishRequestResponseObject); ok {
		return validResponse.VisitFailAnnouncementPublishRequestResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
